version: "3.9"
services:
  web:
    build: .
    container_name: faceapp
    environment:
      - PORT=8000
      - INSIGHTFACE_HOME=/root/.insightface
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ${HOME}/.insightface:/root/.insightface
      - ./data:/app/data
    restart: unless-stopped
